spring:
  profiles:
    active: dev
---
spring:
  port: 8201
spring:
  profiles: dev #开发环境
  appliction:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
spring:
  port: 8201
spring:
  profiles: test #开发环境
  appliction:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/